version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./..:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./..:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'test'
            MYSQL_DATABASE: 'test_db'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 33061:3306
volumes:
    mysqldata: {}
