language: php

php:
  - '7.4'
  - '8.2'
  - '8.3'

before_script:
 - php composer.phar install --dev --no-interaction --prefer-source

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text

