language: php

php:
  - '5.6'
  - '7.4'

before_script:
 - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --no-interaction --prefer-source

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text

