<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'index_controller' => '/app_skeleton/controllers/Index_Controller.php',
                'pff\\acontroller' => '/core/abstract/AController.php',
                'pff\\amodel' => '/core/abstract/AModel.php',
                'pff\\amodeldb' => '/core/abstract/AModelDB.php',
                'pff\\amodelorm' => '/core/abstract/AModelORM.php',
                'pff\\amodule' => '/core/abstract/AModule.php',
                'pff\\app' => '/App.php',
                'pff\\aview' => '/core/abstract/AView.php',
                'pff\\config' => '/Config.php',
                'pff\\configexception' => '/exceptions/ConfigException.php',
                'pff\\flayout' => '/core/factories/FLayout.php',
                'pff\\fview' => '/core/factories/FView.php',
                'pff\\helperexception' => '/exceptions/HelperException.php',
                'pff\\helpermanager' => '/core/HelperManager.php',
                'pff\\hookexception' => '/exceptions/HookException.php',
                'pff\\hookmanager' => '/core/HookManager.php',
                'pff\\iafterhook' => '/core/interfaces/IAfterHook.php',
                'pff\\iafterviewhook' => '/core/interfaces/IAfterViewHook.php',
                'pff\\ibeforehook' => '/core/interfaces/IBeforeHook.php',
                'pff\\ibeforesystemhook' => '/core/interfaces/IBeforeSystemHook.php',
                'pff\\ibeforeviewhook' => '/core/interfaces/IBeforeViewHook.php',
                'pff\\iconfigurablemodule' => '/core/interfaces/IConfigurableModule.php',
                'pff\\ihookprovider' => '/core/interfaces/IHookProvider.php',
                'pff\\irenderable' => '/core/interfaces/IRenderable.php',
                'pff\\layoutphp' => '/core/LayoutPHP.php',
                'pff\\layoutsmarty' => '/core/LayoutSmarty.php',
                'pff\\moduleexception' => '/exceptions/ModuleException.php',
                'pff\\modulemanager' => '/core/ModuleManager.php',
                'pff\\modules\\alogger' => '/modules/logger/ALogger.php',
                'pff\\modules\\apasswordchecker' => '/modules/auth/APasswordChecker.php',
                'pff\\modules\\auth' => '/modules/auth/Auth.php',
                'pff\\modules\\authexception' => '/modules/auth/exceptions/AuthException.php',
                'pff\\modules\\automaticheaderfooter' => '/modules/automatic_header_footer/AutomaticHeaderFooter.php',
                'pff\\modules\\automaticheaderfooterexception' => '/modules/automatic_header_footer/exceptions/AutomaticHeaderFooterException.php',
                'pff\\modules\\configvars' => '/modules/config_var/ConfigVars.php',
                'pff\\modules\\cookies' => '/modules/cookies/Cookies.php',
                'pff\\modules\\defaultcontroller' => '/modules/default_controller/DefaultController.php',
                'pff\\modules\\encryption' => '/modules/encryption/Encryption.php',
                'pff\\modules\\exceptionhandler' => '/modules/exception_handler/ExceptionHandler.php',
                'pff\\modules\\htmlpurifier' => '/modules/htmlpurifier/HtmlPurifier.php',
                'pff\\modules\\logger' => '/modules/logger/Logger.php',
                'pff\\modules\\loggerconfigexception' => '/modules/logger/exceptions/LoggerConfigException.php',
                'pff\\modules\\loggerexception' => '/modules/logger/exceptions/LoggerException.php',
                'pff\\modules\\loggerfile' => '/modules/logger/custom_loggers/LoggerFile.php',
                'pff\\modules\\loggerfileexception' => '/modules/logger/exceptions/LoggerFileException.php',
                'pff\\modules\\mail' => '/modules/mail/Mail.php',
                'pff\\modules\\mainlayout' => '/modules/main_layout/Mainlayout.php',
                'pff\\modules\\md5passwordchecker' => '/modules/auth/password_checkers/Md5PasswordChecker.php',
                'pff\\modules\\mobileviews' => '/modules/mobile_views/MobileViews.php',
                'pff\\modules\\mobileviewsexception' => '/modules/mobile_views/exceptions/MobileViewsException.php',
                'pff\\modules\\multilanguage' => '/modules/multilanguage/MultiLanguage.php',
                'pff\\modules\\networkhelper' => '/modules/network_helper/NetworkHelper.php',
                'pff\\modules\\paypal' => '/modules/paypal/Paypal.php',
                'pff\\modules\\paypalexception' => '/modules/paypal/exceptions/PaypalException.php',
                'pff\\modules\\search' => '/modules/search/SearchModule.php',
                'pff\\modules\\searcher' => '/modules/search/Searcher.php',
                'pff\\modules\\session' => '/modules/session/Session.php',
                'pff\\modules\\sha256passwordchecker' => '/modules/auth/password_checkers/Sha256PasswordChecker.php',
                'pff\\modules\\test' => '/modules/test/Test.php',
                'pff\\modules\\tidycleaner' => '/modules/tidy/TidyCleaner.php',
                'pff\\modules\\url' => '/modules/url/Url.php',
                'pff\\pffexception' => '/exceptions/PffException.php',
                'pff\\routingexception' => '/exceptions/RoutingException.php',
                'pff\\viewexception' => '/exceptions/ViewException.php',
                'pff\\viewphp' => '/core/ViewPHP.php',
                'pff\\viewsmarty' => '/core/ViewSmarty.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
