#!/bin/bash
green='\e[0;32m'
GREEN='\e[1;32m'
red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m' # No Color

function help() {
    echo -e "${NC}-f    Force the update";
}

force=false

function copy_file() {
    local src="$1"
    local dest="$2"
    local label="$3"

    if [ -e "$dest" ] || [ -L "$dest" ]; then
        if [ "$force" == "true" ]; then
            cp -f "$src" "$dest"
            echo -e "${GREEN}[OK]${NC} (${label} overwritten)"
        else
            echo -e "${GREEN}[OK]${NC} (${label} already present, skipped)"
        fi
    else
        cp "$src" "$dest"
        echo -e "${GREEN}[OK]"
    fi
}

echo -e "${GREEN}========== \n${BLUE} pf${RED}f${GREEN}2 ${BLUE}update \n${GREEN}=========="

# Gets the parameters
while getopts ":f" opt; do
    case $opt in
        f)
            force=true
            echo -e "${red}Force update!"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            echo -e "\n"
            help
            exit
            ;;
    esac
done


# command line dependecies"
#CMDS="curl"
PKGS=""
#######################################
# START
#######################################
fail=false


# GENERATE tmp FOLDER
echo -ne "\n${CYAN}Checking tmp directory..."
tmp=`pwd`
if [ ! -d "tmp" ]
then
    mkdir tmp
    chmod -R 777 tmp
    echo -e "${GREEN}[OK]"
else
    chmod -R 777 tmp
    echo -e "${GREEN}[OK]${NC} (tmp/ folder already present)"
fi
cd $tmp

# GENERATE proxy FOLDER
echo -ne "\n${CYAN}Checking proxy directory..."
tmp=`pwd`
if [ ! -d "app/proxies" ]
then
    mkdir app/proxies
    chmod 777 app/proxies
    echo -e "${GREEN}[OK]"
else
    chmod 777 app/proxies
    echo -e "${GREEN}[OK]${NC} (app/proxies folder already present)"
fi
cd $tmp

#Creating cli-config for doctrine
echo -ne "\n${CYAN}Updating cli-config for doctrine"
copy_file vendor/stonedz/pff2/cli-config.php ./cli-config.php "cli-config.php"


echo -ne "\n${CYAN}Updating index.php"
copy_file vendor/stonedz/pff2/resources/site_skeleton/index.php ./index.php "index.php"


# Final message
if [ "$fail" == "false" ]
then
    echo -e "\n${NC}Everything should be in place :D Have fun!"
else
    echo -e "\n${red}Something went wrong!${NC}"
fi
