#!/bin/bash
green='\e[0;32m'
GREEN='\e[1;32m'
red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m' # No Color

function help() {
    echo -e "${NC}-f    Force the update";
}

echo -e "${GREEN}========== \n${BLUE} pf${RED}f${GREEN}2 ${BLUE}update \n${GREEN}=========="

# Gets the parameters
while getopts ":f" opt; do
    case $opt in
        f)
            force=true
            echo -e "${red}Force update!"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            echo -e "\n"
            help
            exit
            ;;
    esac
done


# command line dependecies"
#CMDS="curl"
PKGS=""
#######################################
# START
#######################################
fail=false
PFF_ROOT="vendor/stonedz/pff2"
if [ ! -d "$PFF_ROOT" ]
then
    PFF_ROOT="."
fi


# GENERATE tmp FOLDER
echo -ne "\n${CYAN}Checking tmp directory..."
tmp=`pwd`
if [ ! -d "tmp" ]
then
    mkdir tmp
    chmod -R 775 tmp
    echo -e "${GREEN}[OK]"
else
    chmod -R 775 tmp
    echo -e "${GREEN}[OK]${NC} (tmp/ folder already present)"
fi
cd $tmp

# GENERATE proxy FOLDER
echo -ne "\n${CYAN}Checking proxy directory..."
tmp=`pwd`
if [ ! -d "app/proxies" ]
then
    mkdir app/proxies
    chmod 775 app/proxies
    echo -e "${GREEN}[OK]"
else
    chmod 775 app/proxies
    echo -e "${GREEN}[OK]${NC} (app/proxies folder already present)"
fi
cd $tmp

#Creating cli-config for doctrine
echo -ne "\n${CYAN}Updating cli-config for doctrine"
if [ -f "$PFF_ROOT/cli-config.php" ]
then
    cp "$PFF_ROOT/cli-config.php" ./cli-config.php
    echo -e "${GREEN}[OK]"
else
    echo -e "${GREEN}[OK]${NC} (skipped: cli-config.php not found)"
fi


echo -ne "\n${CYAN}Updating index.php"
if [ -f "$PFF_ROOT/resources/site_skeleton/index.php" ]
then
    cp "$PFF_ROOT/resources/site_skeleton/index.php" ./index.php
    echo -e "${GREEN}[OK]"
else
    echo -e "${GREEN}[OK]${NC} (skipped: site_skeleton/index.php not found)"
fi

echo -ne "\n${CYAN}Updating development docker files"
mkdir -p development
if [ -f "$PFF_ROOT/development/compose.yaml" ]
then
    cp "$PFF_ROOT/development/compose.yaml" development/compose.yaml
fi
if [ -f "$PFF_ROOT/development/nginx.conf" ]
then
    cp "$PFF_ROOT/development/nginx.conf" development/nginx.conf
fi
if [ -f "$PFF_ROOT/development/PHP.Dockerfile" ]
then
    cp "$PFF_ROOT/development/PHP.Dockerfile" development/PHP.Dockerfile
fi
echo -e "${GREEN}[OK]"


# Final message
if [ "$fail" == "false" ]
then
    echo -e "\n${NC}Everything should be in place :D Have fun!"
else
    echo -e "\n${red}Something went wrong!${NC}"
fi
