#!/bin/bash
green='\e[0;32m'
GREEN='\e[1;32m'
red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m' # No Color

function help() {
    echo -e "${NC}-f    Force the update";
}

echo -e "${GREEN}========== \n${BLUE} pf${RED}f${GREEN}2 ${BLUE}init \n${GREEN}=========="

# Gets the parameters
while getopts ":f" opt; do
    case $opt in
        f)
            force=true
            echo -e "${red}Force update!"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            echo -e "\n"
            help
            exit
            ;;
    esac
done


# command line dependecies"
#CMDS="curl"
PKGS=""
#######################################
# START
#######################################
fail=false


# GENERATE tmp FOLDER
echo -ne "\n${CYAN}Checking tmp directory..."
tmp=`pwd`
if [ ! -d "tmp" ]
then
    mkdir tmp
    chmod -R 777 tmp
    echo -e "${GREEN}[OK]"
else
    chmod -R 777 tmp
    echo -e "${GREEN}[OK]${NC} (tmp/ folder already present)"
fi
cd $tmp

# GENERATE proxy FOLDER
echo -ne "\n${CYAN}Checking proxy directory..."
tmp=`pwd`
if [ ! -d "app/proxies" ]
then
    mkdir app/proxies
    chmod 777 app/proxies
    echo -e "${GREEN}[OK]"
else
    chmod 777 app/proxies
    echo -e "${GREEN}[OK]${NC} (app/proxies folder already present)"
fi
cd $tmp

#Creating cli-config for doctrine
echo -ne "\n${CYAN}Updating cli-config for doctrine"
rm cli-config.php
cp vendor/stonedz/pff2/scripts/cli-config.php .
echo -e "${GREEN}[OK]"


echo -ne "\n${CYAN}Updating cli-config for doctrine"
rm index.php
cp vendor/stonedz/pff2/resources/site_skeleton/index.php .
echo -e "${GREEN}[OK]"


# Final message
if [ "$fail" == "false" ]
then
    echo -e "\n${NC}Everything should be in place :D Have fun!"
else
    echo -e "\n${red}Something went wrong!${NC}"
fi
